### ISSUE TITLE
Peer Review #3 Lexi Knight

### ISSUE THREAD

**Issue by LexiKnight** [HaoweiFan0912/The-2024-U.S.-Presidential-Election-Forecast#2]
Summary
The number of commits thus far is excellent! The first part of the scripts are great but the rest of the scripts as well as the paper itself have not been changed from the starter folder. 

Strong positive points:
- The first half of the scripts are well done. 
- the outline for the paper is present and you have noted what needs to be done. This shows organization
- there is some good analysis done on the model in the appendix section however this may be from the starter folder as its incomplete. 

Critical improvements needed:
- delete 00-simulate_data.py and 07-replications as these are not needed
- need to complete script 04-test-analysis_data,  05-exploratory_data_analysis, 06-model_data and 08-fix_styler. The preamble still has the profs name and date. Is does not appear that you've made any changes from the starter folder. Please review these!
- missing creative title and author
- abstract missing. 1) what was done, 2) what was found, and 3) why this matters (all at a high level). This is important as most people skim the abstract to determine whether to read on or not.
- data section is limited. Needs 
- results section is missing. Be sure to organize the results in neat subsections specific to the dataset.
- discussion is missing
- update the other folder to include llm usage, literature and sketches. These are very important
Suggestions for improvement and Evaluation:
- shorten repo name 
- update README - provide a better overview as well as delete the "some checks" section
- add additional subsections for the data section in addition to the model section. This could include software and r-packages, methodology (data collection, data cleaning, data analysis), features.
- For the figures, i suggest changing the text/font of the figures for excellence. ChatGPT can suggest code and different styles
provide a more creative title and think about adding a subtitle. ChatGPT is great at this.
- add an introduciton. you did a good job of outlining, just need to write it. 
- include literature for the introduction and be sure to cite it and upload them to the literature folder.

Estimated overall mark:
40 out of 126.

Any other comments:
You're off to a great start but have some work to do! There is great potential so keep it up!

**Comment by HaoweiFan0912** [comment]
Thanks for the comments, issues are fixed.
